

services:
  backend:
    build: .
    container_name: andon-backend
    ports:
      - "3000:3000"
    env_file:
      - .env
    restart: always
    depends_on:
      - db
    volumes:
      - .:/app
      - /app/node_modules

  db:
    image: postgres:15
    container_name: andon-db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: bettercallsundeep1234
      POSTGRES_DB: Andon_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always

volumes:
  pgdata:
